services:
  api:
    build:
      context: .
    ports:
      - "8001:8000"
    environment:
      - PORT=8000
      - MONGODB_URL
      - ROOT_PATH
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_SERVICE_NAME
networks:
  default:
    name: winds-mobi
