services:
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    ports:
      - "8002:4317"
    volumes:
      - ./config/local/opentelemetry-collector.yaml:/config.yaml
    environment:
      - ENVIRONMENT=local
      - SENTRY_URL
      - UPTRACE_URL
    command: "--config /config.yaml"
networks:
  default:
    name: winds-mobi
