version: '3.9'

services:
  api:
    build:
      context: .
    profiles:
      - application
    ports:
      - "8001:8000"
    environment:
      PORT: 8000
      MONGODB_URL: ${MONGODB_URL}
      OPENAPI_PREFIX: ${OPENAPI_PREFIX}
    networks:
      - winds-mobi-providers

networks:
  winds-mobi-providers:
    external: true
