[tool.poetry]
name = "winds-mobi-api"
description = "Python standalone asyncIO API that provides different endpoints to get weather data from winds.mobi mongodb."
version = "0.0.0"
authors = ["winds.mobi"]
license = "	AGPL-3.0-only"
packages = [
    { include = "winds_mobi_api" },
]

[tool.poetry.dependencies]
python = "3.7.*"

aiocache = "0.10.1"
fastapi = "0.35.0"
motor = "2.0"
parse-accept-language = "0.1.2"
pyaml = "19.4.1"
scipy = "1.2.1"
sentry-asgi = "0.2.0"
sentry-sdk = "0.9.5"
stop-words = "2018.7.23"
ujson = "1.35"
uvicorn = "0.7.0"

[tool.poetry.dev-dependencies]
black = "21.12b0"
flake8 = "5.0.4"
locust = "latest"
pytest = "7.1.2"
python-dotenv = "latest"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
force-exclude = '''
'''
