[tool.poetry]
name = "winds-mobi-api"
description = "Python standalone asyncIO API that provides different endpoints to get weather data from winds.mobi mongodb."
version = "0.0.0"
authors = ["winds.mobi"]
license = "	AGPL-3.0-only"
packages = [
    { include = "winds_mobi_api" },
]

[tool.poetry.dependencies]
python = "3.10.*"

aiocache = "0.11.1"
fastapi = "0.79.0"
motor = "3.0"
parse-accept-language = "0.1.2"
pyaml = "21.10.1"
pydantic = "1.9.2"
scipy = "1.9.0"
sentry-asgi = "0.2.0"
sentry-sdk = "1.9.4"
stop-words = "2018.7.23"
ujson = "5.4.0" # Optional dependency used by aiocache
uvicorn = {extras = ["standard"], version = "0.17.6"}

[tool.poetry.dev-dependencies]
black = "22.6.0"
flake8 = "5.0.4"
isort = "5.10.1"
locust = "latest"
pytest = "7.1.2"
python-dotenv = "latest"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
