version: 1
disable_existing_loggers: False
formatters:
  console:
    format: "%(asctime)s %(levelname)s [%(name)s] | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S%z"
handlers:
  console:
    class: logging.StreamHandler
    formatter: console
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: INFO
  uvicorn.access:
    level: INFO
  winds_mobi_api:
    level: DEBUG
root:
  handlers: [ console ]
  level: INFO
